# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2022 Aalto University

MAJOR_VERSION = 2
MINOR_VERSION = 0
PATCH_VERSION = 0
EXT_VERSION = "rc.3"

EXT_VERSION_SUFFIX = f"-{EXT_VERSION}" if len(EXT_VERSION) > 0 else ""

VERSION = f"{MAJOR_VERSION}.{MINOR_VERSION}.{PATCH_VERSION}{EXT_VERSION_SUFFIX}"
