# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2021 Aalto University

MAJOR_VERSION = 0
MINOR_VERSION = 2
PATCH_VERSION = 0
EXT_VERSION = "alpha.1"

VERSION = f"{MAJOR_VERSION}.{MINOR_VERSION}.{PATCH_VERSION}-{EXT_VERSION}"
