# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2023 Aalto University

name: Jax Compatibility Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, "*stable" ]

jobs:
  unittests-with-minimum-jaxlib:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        jax-version: [
          0.4.1, 0.4.14
        ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
    - name: Install dependencies
      run: |
        python -m pip install "jax[minimum-jaxlib]==${{ matrix.jax-version }}"
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest tests/
