# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Jax Compatibility Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jax-version: [0.2.10, 0.2.12, 0.2.13]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
    - name: Install dependencies
      run: |
        python -m pip install "jax[minimum-jaxlib]==${{ matrix.jax-version }}"
        python -m pip install .[tests]
    - name: Test with pytest
      run: |
        pytest tests/
