# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2023 Aalto University, © 2024 Aalto University

name: Jax Compatibility Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, "*stable" ]

jobs:
  unittests-with-current-jaxlib:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        jax-version: [
          0.3.15, 0.3.17, 0.3.23, 0.3.25, 0.4.14
        ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
    - name: Install dependencies
      run: |
        python -m pip install "jax[cpu]==${{ matrix.jax-version }}" -f https://storage.googleapis.com/jax-releases/jax_releases.html
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest tests/
