# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2021 Aalto University

name: Jax Compatibility Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, "*stable" ]

jobs:
  unittests-with-minimum-jaxlib:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jax-version: [
          0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.2.16,
          0.2.17, 0.2.18, 0.2.19, 0.2.20, 0.2.21,
          0.2.22, 0.2.27, 0.3.1, 0.3.13, 0.3.15,
          0.3.17, 0.3.23
        ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
    - name: Install dependencies
      run: |
        python -m pip install "jax[minimum-jaxlib]==${{ matrix.jax-version }}"
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest tests/
