# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2026 Aalto University

name: Native code tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, "*stable" ]

jobs:
  test_native_intel:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        force_generic: ['On', 'Off']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install environment
      run: |
        sudo apt-get update
        sudo apt-get install gcc g++ cmake python3 python3-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DBUILD_TESTING=On -DFORCE_GENERIC=${{ matrix.force_generic }} -DCMAKE_BUILD_TYPE=Release ..
        make
    - name: Run CPU kernel tests
      run: |
        cd build
        ./cpu_kernel_tests

  test_native_arm_cross:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        force_generic: ['On', 'Off']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build cross-compilation container
      run: docker build -t arm-cross-builder arm_container
    - name: Build and run in container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/work/src \
          -e FORCE_GENERIC=${{ matrix.force_generic }} \
          arm-cross-builder
